### ISSUE TITLE
LaTeX Error: No counter 'zref@unique' defined.

### ISSUE THREAD

**Issue by bibeauel** [ho-tex/zref#15] opened 2022-04-14 14:41 UTC
Not sure if this is related to the zref package. I do not use this package and when I compile using the latest Mikitex distribution every location I have\inlude{file.tex} the error pops up: No counter 'zref@unique' defined.  This only occurs on my computer that has the very recednt Mikitex distribution. It is an issue with the Mikitex distribution as my other 2 computers do nto show this error. Any idea where to look.

**Comment by FrankMittelbach** [comment] 2022-04-14 15:01
This is a duplicate of #14 (which also contains a workaround).

**Closed** 2023-09-14 09:14 UTC
