### ISSUE TITLE
pdftex primitives require luatex85.sty-ish logic in modern LuaLaTeX

### ISSUE THREAD

**Issue by Quoor8ee** [ho-tex/zref#6] opened 2020-02-29 22:41 UTC
I'm cleaning up use cases of the transitional compatibility package luatex85. This made some unmitigated dependencies of `zref` modules on `\pdf...` primitives visible:

- `\pdfhorigin`, `\pdfvorigin`, `\pdfpageheight`, `\pdfpagewidth` are referred to in `zref-pagelayout`, but the checks within `zref-abspos` are insufficient
- In contrast, `\pdflastxpos`, `\pdflastxpos`, `\pdfsavepos` work well with sanitised by `zref-savepos`
- `\pdfpageattr` and ` \pdfpagesattr` are identified as absent in modern (>TL 2016) LuaTeX: the log file informs you with `Package zref-pageattr Info: \pdfpage{,s}attr is not available.`; still `\page{,s}attr` is a LuaTeX primitive that easily could be mapped to that (just as luatex85 does).

MWE (tested on recently-frozen TL2019 trunk):
```
%!lualatex %
\documentclass{article}

\iftrue% C&P from luatex85.sty {
%\else  % Uncomment to break MWE
\protected\edef\pdfvorigin{\pdfvariable vorigin}
\protected\edef\pdfhorigin             {\pdfvariable horigin}
\let\pdfpageheight       \pageheight
\let\pdfpagewidth       \pagewidth
\fi% }

\usepackage{zref-user}
\usepackage{zref-abspos}
\usepackage{zref-savepos}
\usepackage{zref-pagelayout}
\makeatletter
\zref@addprop{savepos}{page}
\zref@addprop{savepos}{textheight}
\zref@addprop{savepos}{pdfvorigin}
\zref@addprop{savepos}{pdfhorigin}
\zref@addprop{savepos}{pdfpageheight}
\zref@addprop{savepos}{pdfpagewidth}
\makeatother

\begin{document}
\LaTeX
\end{document}
```

Side question: I got this right that, apparently, the `\ifpdf` conditional is no longer bijective to the existence of all the neat `\pdf*` primitives that we're used to from pdfTeX (and LuaTeX<=0.80)? The only way to ensure their existence is `\ifpdftex` then?

**Comment by davidcarlisle** [comment] 2020-02-29 23:00
oh thanks for this report, that's odd.... The luatex primitive name changes breaking Heiko's packages was the main reason for setting up this ho-tex group, I thought I'd found all the lurking \pdf... commands but I clearly missed these in zref. Will fix...

I'm not sure I understood your remark about `\ifpdf` it was never very related to the existence of \pdfxxx primitives. It was/is true if pdftex is in pdf output mode, but most of the primitives such as \pdforigin, \pdfsavepos etc are available in dvi mode as well, when \ifpdf is false.  It's now also true if luatex is in pdf output mode and none of the \pdf... commands are primitive.

**Comment by u-fischer** [comment] 2020-02-29 23:17
@davidcarlisle  I think instead of defining the commands one should add the properties with luatex commands in the sty:

~~~~
\documentclass{article}
\usepackage{iftex}
\usepackage{zref-user}
\usepackage{zref-abspos}
\usepackage{zref-savepos}
\usepackage{zref-pagelayout}
\makeatletter
%new for luatex:
\ifluatex
\zref@newprop*{pdfvorigin}%
                             [\number\pdfvariable vorigin]% hash-ok
                             {\number\pdfvariable vorigin}%
\zref@addprop{thepage}{pdfvorigin}                             
\zref@newprop*{pdfhorigin}%
                             [\number\pdfvariable horigin]% hash-ok
                             {\number\pdfvariable horigin}%
\zref@addprop{thepage}{pdfhorigin}                              
\zref@newprop*{pdfpageheight}%
                             [\number\pageheight]% hash-ok
                             {\number\pageheight}%
\zref@addprop{thepage}{pdfpageheight}                              
\zref@newprop*{pdfpagewidth}%
                             [\number\pagewidth]% hash-ok
                             {\number\pagewidth}%  
\zref@addprop{thepage}{pdfpagewidth}                             
\fi                                                       
\zref@addprop{savepos}{page}
\zref@addprop{savepos}{textheight}
\zref@addprop{savepos}{pdfvorigin}
\zref@addprop{savepos}{pdfhorigin}
\zref@addprop{savepos}{pdfpageheight}
\zref@addprop{savepos}{pdfpagewidth}
\makeatother

\begin{document}
\LaTeX \zlistpagelayout
\end{document}
~~~~

This gives for me the same values in the log for pdflatex and lualatex

**Comment by davidcarlisle** [comment] 2020-02-29 23:21
@u-fischer  agreed it's always better to avoid defining the pdftex names. It is still done that way in a few of the ho-tex packages as there were a lot to fix in a short time:-)

**Comment by u-fischer** [comment] 2020-02-29 23:23
@davidcarlisle I'm  not quite sure what the \directlua in the style does, but I suspect most if it can go. And the `\ifnum\luatexversion<39 ` certainly.

**Comment by davidcarlisle** [comment] 2020-02-29 23:28
@u-fischer  it's calling tex.enableprimitives to define \pdfvorigin etc (then failing) but I think for latex we can assume luatex 1.x and assume the primitives are enabled so this can be vastly simplified I guess.

**Comment by u-fischer** [comment] 2020-02-29 23:34
@davidcarlisle  yes, I guess "vastly" means here, "remove everything in the \ifluatex" ;-)

But one has to avoid the these lines are called in luatex together with my code. If luatex85 is loaded zref would try to define the property twice and then error:

~~~~
   \ZREF@pl@ListEntry{pdfpagewidth}%
        \ZREF@pl@ListEntry{pdfpageheight}%
        \ZREF@pl@ListEntry{pdfhorigin}%
        \ZREF@pl@ListEntry{pdfvorigin}%
~~~~

**Comment by Quoor8ee** [comment] 2020-02-29 23:36
Yeah, that's my point. I wondered why `zref-abspos` relies on `\ifpdf` to ensure existence of `\pdf{h,v}origin`, since there are false positives (DVI) as well as false negatives (LuaTeX>=0.85). I don't have an overview on the use cases of `\ifpdf`, but `\pdf*` primitive sanitising isn't one. Thanks for clarifying.

**Comment by davidcarlisle** [comment] 2020-02-29 23:43
> I wondered why zref-abspos relies on \ifpdf to ensure existence of \pdf{h,v}origin,

ah something else to fix...

We'll build something in a branch and probably ask you to review when it's there! thanks for the comments.

**Comment by davidcarlisle** [comment] 2020-03-01 15:37
@u-fischer 

```
\documentclass{article}

\usepackage{zref-pageattr}

\begin{document}

\end{document}
```

gives (with lualatex)

```
Package zref-pageattr Info: \pdfpageattr is not available.
Package zref-pageattr Info: \pdfpagesattr is not available.
```

which I think means the last remaining `\directlua` block is doing obsolete tests and can go?

```
\ifluatex
  \ifnum\luatexversion<39 %
  \else
    \begingroup
      \escapechar=-1 %
      \def\ZREF@temp#1{%
        \ltx@IfUndefined{\string#1}{%
          \let#1\ltx@undefined
          \directlua{%
            if tex.enableprimitives then %
              tex.enableprimitives('', {'\string#1'})%
            end%
          }%
          \ltx@ifundefined{\string#1}{%
          }{%
            \global#1=#1%
            \@PackageInfoNoLine{zref-pageattr}{%
              \string#1 enabled%
            }%
          }%
        }{}%
      }%
      \ZREF@temp\pdfpageattr
      \ZREF@temp\pdfpagesattr
    \endgroup
  \fi
\fi
```

should be I think

 if luatex then if old luatex die else use `\pdfvariable pageattr`


But I don't feel confident to write test cases to check zref is working as intended here??

**Comment by u-fischer** [comment] 2020-03-01 15:41
@davidcarlisle  just when I thought I had done it ;-). I pushed in the branch a change for abspos and pagelayout. You could check these and I will look and pageattr. 

(attention: the name of the zref-property is always e.g. pdfpagewidth, only the command is \pagewidth in luatex. So there are still various pdfpagewidth around).

**Comment by davidcarlisle** [comment] 2020-03-01 16:06
@u-fischer  as @Quoor8ee  commented above the `\ifpdf` tests in abspos still look suspicious to me

```
\let\ZREF@temp\ltx@two
\ltx@IfUndefined{pdfhorigin}{}{%
  \ifpdf
    \let\ZREF@temp\ltx@zero
  \fi
}
\ifluatex
 \ifpdf
  \let\ZREF@temp\ltx@zero
 \fi
\fi

```

forgetting luatex for a moment `\pdfhorigin` works in dvi and pdf mod in pdftex (for decades, if not originally)  so it's not clear why the cases 1 or 2 should ever get used in luatex or pdftex, unless I am missing something?

```
\ifcase\ZREF@temp
  \def\ZREF@abspos@origin@x#1{%
    \zref@extract{#1}{pdfhorigin}%
  }%
\or
  \def\ZREF@abspos@origin@x#1{%
    4736286%
  }%
\or
  \def\ZREF@abspos@origin@x#1{%
    \numexpr\mag/1000*\dimexpr 1truein\relax\relax
  }%
\fi

```

**Comment by u-fischer** [comment] 2020-03-01 16:23
@davidcarlisle  well case one is for example for xelatex. I wasn't sure about case 2, e.g. if there are cases where you want to take \mag into account and if it could give a different result than \pdfhorigin so I left it in.

**Comment by davidcarlisle** [comment] 2020-03-01 16:36
@u-fischer  yes but

\ltx@IfUndefined{pdfhorigin}{}{%
  \ifpdf
    \let\ZREF@temp\ltx@zero
  \fi
}

says that in pdftex ignore \pdfhorigin in dvi mode even if it is defined which doesn't seem right (even if it's right that \mag should be checked in that case) I'll see if I can make a test case where \pdfhorigin is set non zero and this does something wrong in dvi mode....

**Comment by davidcarlisle** [comment] 2020-03-02 21:32
@u-fischer  @Quoor8ee  I can't see any cases where `\mag` or `\pdf[vh]origin` behaviour depends on pdfmode so I think the `\ifpdf` in zref-abspos should go and  (for example)

```
\ltx@IfUndefined{pdfvorigin}{}{%
  \ifpdf
    \let\ZREF@temp\ltx@zero
  \fi
}
```

should be

```
\ltx@IfUndefined{pdfvorigin}{}{%
    \let\ZREF@temp\ltx@zero
}
```

although I wish I was a bit more confident...

**Comment by davidcarlisle** [comment] 2020-03-02 21:56
Removed `\ifpdf` in 7561492

**Comment by davidcarlisle** [comment] 2020-03-04 21:26
updated zref submitted to ctan, thanks for the report.

**Closed by davidcarlisle** 2020-03-04 21:26 UTC
